groups:
  - name: devs
    reviewers: 2
    internal_reviewers: 0
    usernames:
      - scsetoptech
      - YoNG-Zaii
      - Ignitedgene
      - rivenbryan
      - eclarees
      - JeremyNathanJusuf
